[%
    T = {
        title = "Check URL",
        created_by = "Plugin created by",
        website = 'Visit our <a href="https://inlibro.com/en/">website</a> for more Koha plugins',

        mainpage_title = "Koha:CheckUrl Plugin",
        check_url_button = "Check URL",

        resultpage_title = "Koha: Check URL Results",
        result_list_title = "Check URL Results",
        all_url_valid = "All URLs are valid",
        back_home_link = "Back to Home",

        error_404 = "404 File not found",
        error_599 = "599 Only http and https URL schemes supported",
        error_595 = "595 Connection refused",
        error_403 = "403 Forbidden",
    }
%]