[%
    T = {
        title = "Check URL",
        created_by = "Cette extension a été créée par",
        website = 'Visitez notre <a href="https://inlibro.com">site web</a> pour d\'autres extensions Koha',

        mainpage_title = "Koha:Extension Check URL",
        check_url_button = "Vérifier les URL",

        resultpage_title = "Koha: Résultats Check URL",
        result_list_title = "Check URL: Résultats",
        all_url_valid = "Toutes les URLs sont valides",
        back_home_link = "Retour à l'acceuil",

        error_404 = "404 Fichier introuvable",
        error_599 = "599 Seuls les protocoles http et https sont acceptés",
        error_595 = "595 Connection refusé",
        error_403 = "403 Non autorisé",
    }
%]